Web Improvements including Cloud Tiling
OCAP2/web pull request #42
Opened 2022-04-14 15:55 UTC by indig0fox

2022-04-14 16:02 UTC, indig0fox commented
- adds leaflet control to show/hide of units/vehicles, side markers, global markers, and projectile markers
- adds leaflet control to select displayed terrain layer, if map has more than just topo rendered
  - supports "Topographic", "Topographic Dark", "Topographic Relief", "Color Relief"
- changes popups over entities to a 'glow white' effect surrounding black text, for easy of seeing units in very close proximity as well as on dark backgrounds
- adds compatibility for LOGIC side objects, which are typically excluded but in some cases have been re-initialized as live entities due to module actions (add editable objects)
- adds "GeneralEvent" class for support with new addon functionality to add generic messaging in event timeline
- minor EN localization improvement on time menu display
- sets up ocap.ui.js setting for useCloudTiles -- will fetch data from a centralized map server and load tiles from there, eliminating the need for server admins to install individual maps

2022-04-22 13:47 UTC, Fank requested changes

2022-04-22 13:47 UTC, Fank commented on static/index.html
> +            <input type="range" id="frameSlider" min="0" value="0" />
In html a / at the end of an element is not needed, its only part of the xhtml specification

2022-04-22 13:47 UTC, Fank commented on static/scripts/localizable.js
>  		"de": "Spieler- und Fahrzeugnamen"
```suggestion
		"de": "Spieler-, Fahrzeug und Projektilnamen"
```

2022-04-22 13:47 UTC, Fank commented on static/scripts/localizable.js
>  		"de": "Verstrichene Missionszeit"
```suggestion
		"de": "In-Game Missionszeit"
```

2022-04-22 13:47 UTC, Fank commented on static/scripts/localizable.js
>  		"de": "Systemzeit"
```suggestion
		"de": "Systemzeit (UTC)"
```

2022-04-22 13:47 UTC, Fank commented on static/scripts/ocap.entity.js
> +	// }
Just remove it when not neede anymore

2022-05-05 14:40 UTC, indig0fox commented
Need assistance in checking local files for installed maps before then loading from remote tileserver.

Currently this uses `ui.useCloudTiles` defined in `/static/scripts/ocap.ui.js` as a hard switch. Instead, check server and if not installed fall back to centralized repository to check.

This is for map.json
https://github.com/OCAP2/web/blob/a10d227b8905eaa5762f487ed919352fa1725fb3/static/scripts/ocap.js#L178-L194

This is for the actual layers
https://github.com/OCAP2/web/blob/a10d227b8905eaa5762f487ed919352fa1725fb3/static/scripts/ocap.js#L386-L403

2026-01-30 17:39 UTC, closed without merging